#version 450

layout(local_size_x = 16,
       local_size_y = 16,
       local_size_z = 1) in;

layout(set = 0, binding = 0) readonly buffer MatrixA
{
	float a[];
};

layout(set = 0, binding = 1) readonly buffer MatrixB
{
	float b[];
};

layout(set = 0, binding = 2) writeonly buffer MatrixC
{
	float c[];
};

layout(set = 0, binding = 3) readonly buffer Dimensions
{
	uint dims[];
};

void main()
{
	uint row = gl_GlobalInvocationID.y;
	uint col = gl_GlobalInvocationID.x;

	uint m = dims[0];
	uint n = dims[1];
	uint k = dims[2];

	if (row >= m || col >= n)
		return;

	float sum = 0.0;

	for (uint i = 0; i < k; ++i)
		sum += a[row * k + i] * b[i * n + col];

	c[row * n + col] = sum;
}